<?php

namespace Gestion\GitesBundle\Repository;

/**
 * ChambresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChambresRepository extends \Doctrine\ORM\EntityRepository
{
}
